### ISSUE TITLE
Release v1.4

### ISSUE THREAD

**Issue by zlatko-michailov** [vog/sha1#16]
Please tag/release v1.4 to mark the "header-only" milestone.

(There are more changes that I would like to make, but I don't want to interfere with "header-only".)

**Comment by vog** [comment]
I'd like to finish #14, then I'll do the release.

**Comment by zlatko-michailov** [comment]
Yes, of course.
I filed this issue to make sure we release 1.4 before we do any other changes.

**Comment by vog** [comment]
Release: https://github.com/vog/sha1/releases/tag/1.4
